export type EmojiEntry = { emoji: string; name: string };

export const EMOJI_LIST: EmojiEntry[] = [
  // ── Smileys & Emotion ──
  { emoji: "😀", name: "grinning face happy" },
  { emoji: "😃", name: "grinning face big eyes happy" },
  { emoji: "😄", name: "grinning face smiling eyes happy" },
  { emoji: "😁", name: "beaming face grin" },
  { emoji: "😆", name: "grinning squinting face laugh" },
  { emoji: "😅", name: "grinning face sweat nervous" },
  { emoji: "🤣", name: "rolling floor laughing rofl" },
  { emoji: "😂", name: "face tears joy laughing cry" },
  { emoji: "🙂", name: "slightly smiling face" },
  { emoji: "🙃", name: "upside down face" },
  { emoji: "😉", name: "winking face wink" },
  { emoji: "😊", name: "smiling face smiling eyes blush happy" },
  { emoji: "😇", name: "smiling face halo angel" },
  { emoji: "🥰", name: "smiling face hearts love" },
  { emoji: "😍", name: "smiling face heart eyes love" },
  { emoji: "🤩", name: "star struck excited" },
  { emoji: "😘", name: "face blowing kiss" },
  { emoji: "😗", name: "kissing face" },
  { emoji: "☺️", name: "smiling face relaxed" },
  { emoji: "😚", name: "kissing face closed eyes" },
  { emoji: "😙", name: "kissing face smiling eyes" },
  { emoji: "🥲", name: "smiling face tear happy sad" },
  { emoji: "😋", name: "face savoring food yum delicious" },
  { emoji: "😛", name: "face tongue" },
  { emoji: "😜", name: "winking face tongue" },
  { emoji: "🤪", name: "zany face crazy wild" },
  { emoji: "😝", name: "squinting face tongue" },
  { emoji: "🤑", name: "money mouth face rich dollar" },
  { emoji: "🤗", name: "hugging face hug" },
  { emoji: "🤭", name: "face hand over mouth oops giggle" },
  { emoji: "🫢", name: "face open eyes hand over mouth" },
  { emoji: "🫣", name: "face peeking eye" },
  { emoji: "🤫", name: "shushing face quiet secret" },
  { emoji: "🤔", name: "thinking face think hmm" },
  { emoji: "🫡", name: "saluting face salute" },
  { emoji: "🤐", name: "zipper mouth face zip" },
  { emoji: "🤨", name: "face raised eyebrow skeptical" },
  { emoji: "😐", name: "neutral face" },
  { emoji: "😑", name: "expressionless face" },
  { emoji: "😶", name: "face without mouth silent" },
  { emoji: "🫥", name: "dotted line face invisible" },
  { emoji: "😏", name: "smirking face smirk" },
  { emoji: "😒", name: "unamused face" },
  { emoji: "🙄", name: "face rolling eyes" },
  { emoji: "😬", name: "grimacing face awkward" },
  { emoji: "🤥", name: "lying face pinocchio" },
  { emoji: "🫨", name: "shaking face" },
  { emoji: "😌", name: "relieved face" },
  { emoji: "😔", name: "pensive face sad" },
  { emoji: "😪", name: "sleepy face" },
  { emoji: "🤤", name: "drooling face drool" },
  { emoji: "😴", name: "sleeping face zzz sleep" },
  { emoji: "😷", name: "face medical mask sick" },
  { emoji: "🤒", name: "face thermometer sick fever" },
  { emoji: "🤕", name: "face head bandage hurt" },
  { emoji: "🤢", name: "nauseated face sick" },
  { emoji: "🤮", name: "face vomiting throw up" },
  { emoji: "🤧", name: "sneezing face sneeze" },
  { emoji: "🥵", name: "hot face overheated" },
  { emoji: "🥶", name: "cold face freezing" },
  { emoji: "🥴", name: "woozy face dizzy drunk" },
  { emoji: "😵", name: "face crossed out eyes dizzy" },
  { emoji: "😵‍💫", name: "face spiral eyes dizzy" },
  { emoji: "🤯", name: "exploding head mind blown" },
  { emoji: "🤠", name: "cowboy hat face" },
  { emoji: "🥳", name: "partying face party celebrate" },
  { emoji: "🥸", name: "disguised face" },
  { emoji: "😎", name: "smiling face sunglasses cool" },
  { emoji: "🤓", name: "nerd face glasses" },
  { emoji: "🧐", name: "face monocle" },
  { emoji: "😕", name: "confused face" },
  { emoji: "🫤", name: "face diagonal mouth" },
  { emoji: "😟", name: "worried face" },
  { emoji: "🙁", name: "slightly frowning face" },
  { emoji: "☹️", name: "frowning face" },
  { emoji: "😮", name: "face open mouth surprised" },
  { emoji: "😯", name: "hushed face" },
  { emoji: "😲", name: "astonished face shocked" },
  { emoji: "😳", name: "flushed face embarrassed" },
  { emoji: "🥺", name: "pleading face puppy eyes" },
  { emoji: "🥹", name: "face holding back tears" },
  { emoji: "😦", name: "frowning face open mouth" },
  { emoji: "😧", name: "anguished face" },
  { emoji: "😨", name: "fearful face scared" },
  { emoji: "😰", name: "anxious face sweat" },
  { emoji: "😥", name: "sad but relieved face" },
  { emoji: "😢", name: "crying face sad tear" },
  { emoji: "😭", name: "loudly crying face sob" },
  { emoji: "😱", name: "face screaming fear" },
  { emoji: "😖", name: "confounded face" },
  { emoji: "😣", name: "persevering face" },
  { emoji: "😞", name: "disappointed face sad" },
  { emoji: "😓", name: "downcast face sweat" },
  { emoji: "😩", name: "weary face tired" },
  { emoji: "😫", name: "tired face exhausted" },
  { emoji: "🥱", name: "yawning face yawn bored" },
  { emoji: "😤", name: "face steam nose angry triumph" },
  { emoji: "😡", name: "enraged face angry red mad" },
  { emoji: "😠", name: "angry face mad" },
  { emoji: "🤬", name: "face symbols mouth cursing swearing" },
  { emoji: "😈", name: "smiling face horns devil" },
  { emoji: "👿", name: "angry face horns devil" },
  { emoji: "💀", name: "skull dead death" },
  { emoji: "☠️", name: "skull crossbones death" },
  { emoji: "💩", name: "pile poo poop" },
  { emoji: "🤡", name: "clown face" },
  { emoji: "👹", name: "ogre monster" },
  { emoji: "👺", name: "goblin monster" },
  { emoji: "👻", name: "ghost" },
  { emoji: "👽", name: "alien extraterrestrial" },
  { emoji: "👾", name: "alien monster space invader" },
  { emoji: "🤖", name: "robot face bot" },
  { emoji: "😺", name: "grinning cat" },
  { emoji: "😸", name: "grinning cat smiling eyes" },
  { emoji: "😹", name: "cat tears joy" },
  { emoji: "😻", name: "smiling cat heart eyes" },
  { emoji: "😼", name: "cat wry smile" },
  { emoji: "😽", name: "kissing cat" },
  { emoji: "🙀", name: "weary cat" },
  { emoji: "😿", name: "crying cat" },
  { emoji: "😾", name: "pouting cat" },
  { emoji: "🙈", name: "see no evil monkey" },
  { emoji: "🙉", name: "hear no evil monkey" },
  { emoji: "🙊", name: "speak no evil monkey" },
  { emoji: "💋", name: "kiss mark lips" },
  { emoji: "💌", name: "love letter envelope heart" },
  { emoji: "💘", name: "heart arrow cupid" },
  { emoji: "💝", name: "heart ribbon gift" },
  { emoji: "💖", name: "sparkling heart" },
  { emoji: "💗", name: "growing heart" },
  { emoji: "💓", name: "beating heart" },
  { emoji: "💞", name: "revolving hearts" },
  { emoji: "💕", name: "two hearts" },
  { emoji: "💟", name: "heart decoration" },
  { emoji: "❣️", name: "heart exclamation" },
  { emoji: "💔", name: "broken heart" },
  { emoji: "❤️‍🔥", name: "heart on fire" },
  { emoji: "❤️‍🩹", name: "mending heart" },
  { emoji: "❤️", name: "red heart love" },
  { emoji: "🩷", name: "pink heart" },
  { emoji: "🧡", name: "orange heart" },
  { emoji: "💛", name: "yellow heart" },
  { emoji: "💚", name: "green heart" },
  { emoji: "💙", name: "blue heart" },
  { emoji: "🩵", name: "light blue heart" },
  { emoji: "💜", name: "purple heart" },
  { emoji: "🤎", name: "brown heart" },
  { emoji: "🖤", name: "black heart" },
  { emoji: "🩶", name: "grey heart" },
  { emoji: "🤍", name: "white heart" },
  { emoji: "💯", name: "hundred points perfect score" },
  { emoji: "💢", name: "anger symbol" },
  { emoji: "💥", name: "collision boom bang explosion" },
  { emoji: "💫", name: "dizzy star" },
  { emoji: "💦", name: "sweat droplets water" },
  { emoji: "💨", name: "dashing away wind fast" },
  { emoji: "🕳️", name: "hole" },
  { emoji: "💬", name: "speech balloon bubble chat" },
  { emoji: "👁️‍🗨️", name: "eye speech bubble" },
  { emoji: "🗨️", name: "left speech bubble" },
  { emoji: "🗯️", name: "right anger bubble" },
  { emoji: "💭", name: "thought balloon thinking" },
  { emoji: "💤", name: "zzz sleeping" },

  // ── Hands & Gestures ──
  { emoji: "👋", name: "waving hand hello hi bye" },
  { emoji: "🤚", name: "raised back hand" },
  { emoji: "🖐️", name: "hand splayed fingers" },
  { emoji: "✋", name: "raised hand stop high five" },
  { emoji: "🖖", name: "vulcan salute spock" },
  { emoji: "🫱", name: "rightwards hand" },
  { emoji: "🫲", name: "leftwards hand" },
  { emoji: "🫳", name: "palm down hand" },
  { emoji: "🫴", name: "palm up hand" },
  { emoji: "🫷", name: "leftwards pushing hand" },
  { emoji: "🫸", name: "rightwards pushing hand" },
  { emoji: "👌", name: "ok hand okay" },
  { emoji: "🤌", name: "pinched fingers italian" },
  { emoji: "🤏", name: "pinching hand small tiny" },
  { emoji: "✌️", name: "victory hand peace sign" },
  { emoji: "🤞", name: "crossed fingers luck" },
  { emoji: "🫰", name: "hand index thumb crossed" },
  { emoji: "🤟", name: "love you gesture" },
  { emoji: "🤘", name: "sign horns rock metal" },
  { emoji: "🤙", name: "call me hand shaka" },
  { emoji: "👈", name: "backhand index pointing left" },
  { emoji: "👉", name: "backhand index pointing right" },
  { emoji: "👆", name: "backhand index pointing up" },
  { emoji: "🖕", name: "middle finger" },
  { emoji: "👇", name: "backhand index pointing down" },
  { emoji: "☝️", name: "index pointing up" },
  { emoji: "🫵", name: "index pointing at viewer" },
  { emoji: "👍", name: "thumbs up good yes like" },
  { emoji: "👎", name: "thumbs down bad no dislike" },
  { emoji: "✊", name: "raised fist power" },
  { emoji: "👊", name: "oncoming fist punch bump" },
  { emoji: "🤛", name: "left facing fist" },
  { emoji: "🤜", name: "right facing fist" },
  { emoji: "👏", name: "clapping hands applause clap" },
  { emoji: "🙌", name: "raising hands hooray praise" },
  { emoji: "🫶", name: "heart hands love" },
  { emoji: "👐", name: "open hands" },
  { emoji: "🤲", name: "palms up together prayer" },
  { emoji: "🤝", name: "handshake deal agree" },
  { emoji: "🙏", name: "folded hands pray please thank you" },
  { emoji: "✍️", name: "writing hand" },
  { emoji: "💅", name: "nail polish" },
  { emoji: "🤳", name: "selfie" },
  { emoji: "💪", name: "flexed biceps muscle strong" },

  // ── People ──
  { emoji: "👶", name: "baby" },
  { emoji: "🧒", name: "child" },
  { emoji: "👦", name: "boy" },
  { emoji: "👧", name: "girl" },
  { emoji: "🧑", name: "person adult" },
  { emoji: "👱", name: "person blond hair" },
  { emoji: "👨", name: "man" },
  { emoji: "🧔", name: "person beard" },
  { emoji: "👩", name: "woman" },
  { emoji: "🧓", name: "older person" },
  { emoji: "👴", name: "old man" },
  { emoji: "👵", name: "old woman" },
  { emoji: "🙍", name: "person frowning" },
  { emoji: "🙎", name: "person pouting" },
  { emoji: "🙅", name: "person gesturing no" },
  { emoji: "🙆", name: "person gesturing ok" },
  { emoji: "💁", name: "person tipping hand" },
  { emoji: "🙋", name: "person raising hand" },
  { emoji: "🧏", name: "deaf person" },
  { emoji: "🙇", name: "person bowing" },
  { emoji: "🤦", name: "person facepalming facepalm" },
  { emoji: "🤷", name: "person shrugging shrug idk" },
  { emoji: "👮", name: "police officer cop" },
  { emoji: "🕵️", name: "detective spy" },
  { emoji: "💂", name: "guard" },
  { emoji: "🥷", name: "ninja" },
  { emoji: "👷", name: "construction worker" },
  { emoji: "🫅", name: "person crown" },
  { emoji: "🤴", name: "prince" },
  { emoji: "👸", name: "princess" },
  { emoji: "👳", name: "person wearing turban" },
  { emoji: "👲", name: "person skullcap" },
  { emoji: "🧕", name: "woman headscarf" },
  { emoji: "🤵", name: "person tuxedo" },
  { emoji: "👰", name: "person veil bride" },
  { emoji: "🤰", name: "pregnant woman" },
  { emoji: "🫃", name: "pregnant man" },
  { emoji: "🫄", name: "pregnant person" },
  { emoji: "🤱", name: "breast feeding" },
  { emoji: "👼", name: "baby angel" },
  { emoji: "🎅", name: "santa claus christmas" },
  { emoji: "🤶", name: "mrs claus christmas" },
  { emoji: "🦸", name: "superhero" },
  { emoji: "🦹", name: "supervillain" },
  { emoji: "🧙", name: "mage wizard" },
  { emoji: "🧚", name: "fairy" },
  { emoji: "🧛", name: "vampire" },
  { emoji: "🧜", name: "merperson mermaid" },
  { emoji: "🧝", name: "elf" },
  { emoji: "🧞", name: "genie" },
  { emoji: "🧟", name: "zombie" },
  { emoji: "🧌", name: "troll" },
  { emoji: "💆", name: "person getting massage" },
  { emoji: "💇", name: "person getting haircut" },
  { emoji: "🚶", name: "person walking" },
  { emoji: "🧍", name: "person standing" },
  { emoji: "🧎", name: "person kneeling" },
  { emoji: "🏃", name: "person running" },
  { emoji: "💃", name: "woman dancing" },
  { emoji: "🕺", name: "man dancing" },
  { emoji: "👫", name: "woman man holding hands couple" },
  { emoji: "👬", name: "men holding hands" },
  { emoji: "👭", name: "women holding hands" },
  { emoji: "💏", name: "kiss couple" },
  { emoji: "💑", name: "couple with heart love" },
  { emoji: "👪", name: "family" },
  { emoji: "🗣️", name: "speaking head" },
  { emoji: "👤", name: "bust silhouette person" },
  { emoji: "👥", name: "busts silhouette people" },
  { emoji: "🫂", name: "people hugging hug" },
  { emoji: "👣", name: "footprints feet" },

  // ── Animals ──
  { emoji: "🐵", name: "monkey face" },
  { emoji: "🐒", name: "monkey" },
  { emoji: "🦍", name: "gorilla" },
  { emoji: "🦧", name: "orangutan" },
  { emoji: "🐶", name: "dog face puppy" },
  { emoji: "🐕", name: "dog" },
  { emoji: "🦮", name: "guide dog" },
  { emoji: "🐕‍🦺", name: "service dog" },
  { emoji: "🐩", name: "poodle" },
  { emoji: "🐺", name: "wolf" },
  { emoji: "🦊", name: "fox" },
  { emoji: "🦝", name: "raccoon" },
  { emoji: "🐱", name: "cat face" },
  { emoji: "🐈", name: "cat" },
  { emoji: "🐈‍⬛", name: "black cat" },
  { emoji: "🦁", name: "lion" },
  { emoji: "🐯", name: "tiger face" },
  { emoji: "🐅", name: "tiger" },
  { emoji: "🐆", name: "leopard" },
  { emoji: "🐴", name: "horse face" },
  { emoji: "🫎", name: "moose" },
  { emoji: "🫏", name: "donkey" },
  { emoji: "🐎", name: "horse racing" },
  { emoji: "🦄", name: "unicorn" },
  { emoji: "🦓", name: "zebra" },
  { emoji: "🦌", name: "deer" },
  { emoji: "🦬", name: "bison buffalo" },
  { emoji: "🐮", name: "cow face" },
  { emoji: "🐂", name: "ox" },
  { emoji: "🐃", name: "water buffalo" },
  { emoji: "🐄", name: "cow" },
  { emoji: "🐷", name: "pig face" },
  { emoji: "🐖", name: "pig" },
  { emoji: "🐗", name: "boar" },
  { emoji: "🐽", name: "pig nose" },
  { emoji: "🐏", name: "ram sheep" },
  { emoji: "🐑", name: "ewe sheep" },
  { emoji: "🐐", name: "goat" },
  { emoji: "🐪", name: "camel" },
  { emoji: "🐫", name: "two hump camel" },
  { emoji: "🦙", name: "llama alpaca" },
  { emoji: "🦒", name: "giraffe" },
  { emoji: "🐘", name: "elephant" },
  { emoji: "🦣", name: "mammoth" },
  { emoji: "🦏", name: "rhinoceros rhino" },
  { emoji: "🦛", name: "hippopotamus hippo" },
  { emoji: "🐭", name: "mouse face" },
  { emoji: "🐁", name: "mouse" },
  { emoji: "🐀", name: "rat" },
  { emoji: "🐹", name: "hamster" },
  { emoji: "🐰", name: "rabbit face bunny" },
  { emoji: "🐇", name: "rabbit bunny" },
  { emoji: "🐿️", name: "chipmunk squirrel" },
  { emoji: "🦫", name: "beaver" },
  { emoji: "🦔", name: "hedgehog" },
  { emoji: "🦇", name: "bat" },
  { emoji: "🐻", name: "bear" },
  { emoji: "🐻‍❄️", name: "polar bear" },
  { emoji: "🐨", name: "koala" },
  { emoji: "🐼", name: "panda" },
  { emoji: "🦥", name: "sloth" },
  { emoji: "🦦", name: "otter" },
  { emoji: "🦨", name: "skunk" },
  { emoji: "🦘", name: "kangaroo" },
  { emoji: "🦡", name: "badger" },
  { emoji: "🐾", name: "paw prints animal" },
  { emoji: "🦃", name: "turkey" },
  { emoji: "🐔", name: "chicken" },
  { emoji: "🐓", name: "rooster" },
  { emoji: "🐣", name: "hatching chick" },
  { emoji: "🐤", name: "baby chick" },
  { emoji: "🐥", name: "front facing baby chick" },
  { emoji: "🐦", name: "bird" },
  { emoji: "🐧", name: "penguin" },
  { emoji: "🕊️", name: "dove peace" },
  { emoji: "🦅", name: "eagle" },
  { emoji: "🦆", name: "duck" },
  { emoji: "🦢", name: "swan" },
  { emoji: "🦉", name: "owl" },
  { emoji: "🦤", name: "dodo" },
  { emoji: "🪶", name: "feather" },
  { emoji: "🦩", name: "flamingo" },
  { emoji: "🦚", name: "peacock" },
  { emoji: "🦜", name: "parrot" },
  { emoji: "🪽", name: "wing" },
  { emoji: "🐦‍⬛", name: "black bird crow raven" },
  { emoji: "🪿", name: "goose" },
  { emoji: "🐸", name: "frog" },
  { emoji: "🐊", name: "crocodile alligator" },
  { emoji: "🐢", name: "turtle tortoise" },
  { emoji: "🦎", name: "lizard" },
  { emoji: "🐍", name: "snake" },
  { emoji: "🐲", name: "dragon face" },
  { emoji: "🐉", name: "dragon" },
  { emoji: "🦕", name: "sauropod dinosaur" },
  { emoji: "🦖", name: "t-rex dinosaur" },
  { emoji: "🐳", name: "spouting whale" },
  { emoji: "🐋", name: "whale" },
  { emoji: "🐬", name: "dolphin" },
  { emoji: "🦭", name: "seal" },
  { emoji: "🐟", name: "fish" },
  { emoji: "🐠", name: "tropical fish" },
  { emoji: "🐡", name: "blowfish puffer" },
  { emoji: "🦈", name: "shark" },
  { emoji: "🐙", name: "octopus" },
  { emoji: "🐚", name: "spiral shell" },
  { emoji: "🪸", name: "coral reef" },
  { emoji: "🪼", name: "jellyfish" },
  { emoji: "🐌", name: "snail" },
  { emoji: "🦋", name: "butterfly" },
  { emoji: "🐛", name: "bug insect caterpillar" },
  { emoji: "🐜", name: "ant" },
  { emoji: "🐝", name: "honeybee bee" },
  { emoji: "🪲", name: "beetle" },
  { emoji: "🐞", name: "lady beetle ladybug" },
  { emoji: "🦗", name: "cricket" },
  { emoji: "🪳", name: "cockroach" },
  { emoji: "🕷️", name: "spider" },
  { emoji: "🕸️", name: "spider web" },
  { emoji: "🦂", name: "scorpion" },
  { emoji: "🦟", name: "mosquito" },
  { emoji: "🪰", name: "fly" },
  { emoji: "🪱", name: "worm" },
  { emoji: "🦠", name: "microbe bacteria germ virus" },

  // ── Plants & Nature ──
  { emoji: "💐", name: "bouquet flowers" },
  { emoji: "🌸", name: "cherry blossom flower" },
  { emoji: "💮", name: "white flower" },
  { emoji: "🪷", name: "lotus flower" },
  { emoji: "🏵️", name: "rosette" },
  { emoji: "🌹", name: "rose flower" },
  { emoji: "🥀", name: "wilted flower" },
  { emoji: "🌺", name: "hibiscus flower" },
  { emoji: "🌻", name: "sunflower" },
  { emoji: "🌼", name: "blossom flower" },
  { emoji: "🌷", name: "tulip flower" },
  { emoji: "🪻", name: "hyacinth flower" },
  { emoji: "🌱", name: "seedling sprout plant" },
  { emoji: "🪴", name: "potted plant" },
  { emoji: "🌲", name: "evergreen tree pine" },
  { emoji: "🌳", name: "deciduous tree" },
  { emoji: "🌴", name: "palm tree" },
  { emoji: "🌵", name: "cactus desert" },
  { emoji: "🌾", name: "sheaf of rice wheat" },
  { emoji: "🌿", name: "herb leaf" },
  { emoji: "☘️", name: "shamrock clover" },
  { emoji: "🍀", name: "four leaf clover lucky" },
  { emoji: "🍁", name: "maple leaf fall autumn" },
  { emoji: "🍂", name: "fallen leaf autumn" },
  { emoji: "🍃", name: "leaf fluttering wind" },
  { emoji: "🪹", name: "empty nest" },
  { emoji: "🪺", name: "nest with eggs" },
  { emoji: "🍄", name: "mushroom" },

  // ── Food & Drink ──
  { emoji: "🍇", name: "grapes" },
  { emoji: "🍈", name: "melon" },
  { emoji: "🍉", name: "watermelon" },
  { emoji: "🍊", name: "tangerine orange mandarin" },
  { emoji: "🍋", name: "lemon" },
  { emoji: "🍌", name: "banana" },
  { emoji: "🍍", name: "pineapple" },
  { emoji: "🥭", name: "mango" },
  { emoji: "🍎", name: "red apple" },
  { emoji: "🍏", name: "green apple" },
  { emoji: "🍐", name: "pear" },
  { emoji: "🍑", name: "peach" },
  { emoji: "🍒", name: "cherries" },
  { emoji: "🍓", name: "strawberry" },
  { emoji: "🫐", name: "blueberries" },
  { emoji: "🥝", name: "kiwi fruit" },
  { emoji: "🍅", name: "tomato" },
  { emoji: "🫒", name: "olive" },
  { emoji: "🥥", name: "coconut" },
  { emoji: "🥑", name: "avocado" },
  { emoji: "🍆", name: "eggplant aubergine" },
  { emoji: "🥔", name: "potato" },
  { emoji: "🥕", name: "carrot" },
  { emoji: "🌽", name: "ear corn" },
  { emoji: "🌶️", name: "hot pepper chili spicy" },
  { emoji: "🫑", name: "bell pepper" },
  { emoji: "🥒", name: "cucumber" },
  { emoji: "🥬", name: "leafy green lettuce" },
  { emoji: "🥦", name: "broccoli" },
  { emoji: "🧄", name: "garlic" },
  { emoji: "🧅", name: "onion" },
  { emoji: "🥜", name: "peanuts" },
  { emoji: "🫘", name: "beans" },
  { emoji: "🌰", name: "chestnut nut" },
  { emoji: "🫚", name: "ginger root" },
  { emoji: "🫛", name: "pea pod" },
  { emoji: "🍞", name: "bread loaf" },
  { emoji: "🥐", name: "croissant" },
  { emoji: "🥖", name: "baguette bread french" },
  { emoji: "🫓", name: "flatbread" },
  { emoji: "🥨", name: "pretzel" },
  { emoji: "🥯", name: "bagel" },
  { emoji: "🥞", name: "pancakes" },
  { emoji: "🧇", name: "waffle" },
  { emoji: "🧀", name: "cheese wedge" },
  { emoji: "🍖", name: "meat on bone" },
  { emoji: "🍗", name: "poultry leg chicken" },
  { emoji: "🥩", name: "cut meat steak" },
  { emoji: "🥓", name: "bacon" },
  { emoji: "🍔", name: "hamburger burger" },
  { emoji: "🍟", name: "french fries" },
  { emoji: "🍕", name: "pizza" },
  { emoji: "🌭", name: "hot dog" },
  { emoji: "🥪", name: "sandwich" },
  { emoji: "🌮", name: "taco" },
  { emoji: "🌯", name: "burrito" },
  { emoji: "🫔", name: "tamale" },
  { emoji: "🥙", name: "stuffed flatbread falafel" },
  { emoji: "🧆", name: "falafel" },
  { emoji: "🥚", name: "egg" },
  { emoji: "🍳", name: "cooking egg fried" },
  { emoji: "🥘", name: "shallow pan food paella" },
  { emoji: "🍲", name: "pot food stew" },
  { emoji: "🫕", name: "fondue" },
  { emoji: "🥣", name: "bowl spoon cereal" },
  { emoji: "🥗", name: "green salad" },
  { emoji: "🍿", name: "popcorn" },
  { emoji: "🧈", name: "butter" },
  { emoji: "🧂", name: "salt" },
  { emoji: "🥫", name: "canned food" },
  { emoji: "🍱", name: "bento box" },
  { emoji: "🍘", name: "rice cracker" },
  { emoji: "🍙", name: "rice ball onigiri" },
  { emoji: "🍚", name: "cooked rice" },
  { emoji: "🍛", name: "curry rice" },
  { emoji: "🍜", name: "steaming bowl noodles ramen" },
  { emoji: "🍝", name: "spaghetti pasta" },
  { emoji: "🍠", name: "roasted sweet potato" },
  { emoji: "🍢", name: "oden" },
  { emoji: "🍣", name: "sushi" },
  { emoji: "🍤", name: "fried shrimp tempura" },
  { emoji: "🍥", name: "fish cake" },
  { emoji: "🥮", name: "moon cake" },
  { emoji: "🍡", name: "dango" },
  { emoji: "🥟", name: "dumpling" },
  { emoji: "🥠", name: "fortune cookie" },
  { emoji: "🥡", name: "takeout box" },
  { emoji: "🦀", name: "crab" },
  { emoji: "🦞", name: "lobster" },
  { emoji: "🦐", name: "shrimp prawn" },
  { emoji: "🦑", name: "squid" },
  { emoji: "🦪", name: "oyster" },
  { emoji: "🍦", name: "soft ice cream" },
  { emoji: "🍧", name: "shaved ice" },
  { emoji: "🍨", name: "ice cream sundae" },
  { emoji: "🍩", name: "doughnut donut" },
  { emoji: "🍪", name: "cookie" },
  { emoji: "🎂", name: "birthday cake" },
  { emoji: "🍰", name: "shortcake cake" },
  { emoji: "🧁", name: "cupcake muffin" },
  { emoji: "🥧", name: "pie" },
  { emoji: "🍫", name: "chocolate bar" },
  { emoji: "🍬", name: "candy sweet" },
  { emoji: "🍭", name: "lollipop" },
  { emoji: "🍮", name: "custard pudding flan" },
  { emoji: "🍯", name: "honey pot" },
  { emoji: "🍼", name: "baby bottle milk" },
  { emoji: "🥛", name: "glass milk" },
  { emoji: "☕", name: "hot beverage coffee tea" },
  { emoji: "🫖", name: "teapot" },
  { emoji: "🍵", name: "teacup" },
  { emoji: "🍶", name: "sake" },
  { emoji: "🍾", name: "bottle popping cork champagne" },
  { emoji: "🍷", name: "wine glass" },
  { emoji: "🍸", name: "cocktail glass martini" },
  { emoji: "🍹", name: "tropical drink" },
  { emoji: "🍺", name: "beer mug" },
  { emoji: "🍻", name: "clinking beer mugs cheers" },
  { emoji: "🥂", name: "clinking glasses champagne toast" },
  { emoji: "🥃", name: "tumbler glass whiskey" },
  { emoji: "🫗", name: "pouring liquid" },
  { emoji: "🥤", name: "cup straw soda" },
  { emoji: "🧋", name: "bubble tea boba" },
  { emoji: "🧃", name: "beverage box juice" },
  { emoji: "🧉", name: "mate" },
  { emoji: "🧊", name: "ice cube" },
  { emoji: "🥢", name: "chopsticks" },
  { emoji: "🍽️", name: "fork knife plate" },
  { emoji: "🍴", name: "fork knife" },
  { emoji: "🥄", name: "spoon" },
  { emoji: "🔪", name: "kitchen knife" },
  { emoji: "🫙", name: "jar" },
  { emoji: "🏺", name: "amphora vase" },

  // ── Travel & Places ──
  { emoji: "🌍", name: "globe europe africa earth world" },
  { emoji: "🌎", name: "globe americas earth world" },
  { emoji: "🌏", name: "globe asia australia earth world" },
  { emoji: "🌐", name: "globe meridians internet world" },
  { emoji: "🗺️", name: "world map" },
  { emoji: "🧭", name: "compass navigation" },
  { emoji: "🏔️", name: "snow capped mountain" },
  { emoji: "⛰️", name: "mountain" },
  { emoji: "🌋", name: "volcano" },
  { emoji: "🗻", name: "mount fuji" },
  { emoji: "🏕️", name: "camping tent" },
  { emoji: "🏖️", name: "beach umbrella" },
  { emoji: "🏜️", name: "desert" },
  { emoji: "🏝️", name: "desert island" },
  { emoji: "🏞️", name: "national park" },
  { emoji: "🏟️", name: "stadium" },
  { emoji: "🏛️", name: "classical building" },
  { emoji: "🏗️", name: "building construction" },
  { emoji: "🧱", name: "brick" },
  { emoji: "🪨", name: "rock stone" },
  { emoji: "🪵", name: "wood log" },
  { emoji: "🛖", name: "hut" },
  { emoji: "🏘️", name: "houses" },
  { emoji: "🏚️", name: "derelict house" },
  { emoji: "🏠", name: "house home" },
  { emoji: "🏡", name: "house garden" },
  { emoji: "🏢", name: "office building" },
  { emoji: "🏣", name: "japanese post office" },
  { emoji: "🏤", name: "post office" },
  { emoji: "🏥", name: "hospital" },
  { emoji: "🏦", name: "bank" },
  { emoji: "🏨", name: "hotel" },
  { emoji: "🏩", name: "love hotel" },
  { emoji: "🏪", name: "convenience store" },
  { emoji: "🏫", name: "school" },
  { emoji: "🏬", name: "department store" },
  { emoji: "🏭", name: "factory" },
  { emoji: "🏯", name: "japanese castle" },
  { emoji: "🏰", name: "castle" },
  { emoji: "💒", name: "wedding chapel" },
  { emoji: "🗼", name: "tokyo tower" },
  { emoji: "🗽", name: "statue liberty" },
  { emoji: "⛪", name: "church" },
  { emoji: "🕌", name: "mosque" },
  { emoji: "🛕", name: "hindu temple" },
  { emoji: "🕍", name: "synagogue" },
  { emoji: "⛩️", name: "shinto shrine" },
  { emoji: "🕋", name: "kaaba" },
  { emoji: "⛲", name: "fountain" },
  { emoji: "⛺", name: "tent camping" },
  { emoji: "🌁", name: "foggy" },
  { emoji: "🌃", name: "night stars" },
  { emoji: "🏙️", name: "cityscape" },
  { emoji: "🌄", name: "sunrise mountains" },
  { emoji: "🌅", name: "sunrise" },
  { emoji: "🌆", name: "cityscape dusk" },
  { emoji: "🌇", name: "sunset" },
  { emoji: "🌉", name: "bridge night" },
  { emoji: "♨️", name: "hot springs" },
  { emoji: "🎠", name: "carousel horse" },
  { emoji: "🛝", name: "playground slide" },
  { emoji: "🎡", name: "ferris wheel" },
  { emoji: "🎢", name: "roller coaster" },
  { emoji: "💈", name: "barber pole" },
  { emoji: "🎪", name: "circus tent" },
  { emoji: "🚂", name: "locomotive train" },
  { emoji: "🚃", name: "railway car" },
  { emoji: "🚄", name: "high speed train" },
  { emoji: "🚅", name: "bullet train" },
  { emoji: "🚆", name: "train" },
  { emoji: "🚇", name: "metro subway" },
  { emoji: "🚈", name: "light rail" },
  { emoji: "🚉", name: "station" },
  { emoji: "🚊", name: "tram" },
  { emoji: "🚝", name: "monorail" },
  { emoji: "🚞", name: "mountain railway" },
  { emoji: "🚋", name: "tram car" },
  { emoji: "🚌", name: "bus" },
  { emoji: "🚍", name: "oncoming bus" },
  { emoji: "🚎", name: "trolleybus" },
  { emoji: "🚐", name: "minibus" },
  { emoji: "🚑", name: "ambulance" },
  { emoji: "🚒", name: "fire engine truck" },
  { emoji: "🚓", name: "police car" },
  { emoji: "🚔", name: "oncoming police car" },
  { emoji: "🚕", name: "taxi cab" },
  { emoji: "🚖", name: "oncoming taxi" },
  { emoji: "🚗", name: "automobile car" },
  { emoji: "🚘", name: "oncoming automobile" },
  { emoji: "🚙", name: "sport utility vehicle suv" },
  { emoji: "🛻", name: "pickup truck" },
  { emoji: "🚚", name: "delivery truck" },
  { emoji: "🚛", name: "articulated lorry truck" },
  { emoji: "🚜", name: "tractor farm" },
  { emoji: "🏎️", name: "racing car" },
  { emoji: "🏍️", name: "motorcycle" },
  { emoji: "🛵", name: "motor scooter" },
  { emoji: "🦽", name: "manual wheelchair" },
  { emoji: "🦼", name: "motorized wheelchair" },
  { emoji: "🛺", name: "auto rickshaw" },
  { emoji: "🚲", name: "bicycle bike" },
  { emoji: "🛴", name: "kick scooter" },
  { emoji: "🛹", name: "skateboard" },
  { emoji: "🛼", name: "roller skate" },
  { emoji: "🚏", name: "bus stop" },
  { emoji: "🛣️", name: "motorway highway road" },
  { emoji: "🛤️", name: "railway track" },
  { emoji: "🛢️", name: "oil drum barrel" },
  { emoji: "⛽", name: "fuel pump gas" },
  { emoji: "🛞", name: "wheel tire" },
  { emoji: "🚨", name: "police car light siren" },
  { emoji: "🚥", name: "horizontal traffic light" },
  { emoji: "🚦", name: "vertical traffic light" },
  { emoji: "🛑", name: "stop sign" },
  { emoji: "🚧", name: "construction" },
  { emoji: "⚓", name: "anchor" },
  { emoji: "🛟", name: "ring buoy life preserver" },
  { emoji: "⛵", name: "sailboat" },
  { emoji: "🛶", name: "canoe kayak" },
  { emoji: "🚤", name: "speedboat" },
  { emoji: "🛳️", name: "passenger ship cruise" },
  { emoji: "⛴️", name: "ferry" },
  { emoji: "🛥️", name: "motor boat" },
  { emoji: "🚢", name: "ship" },
  { emoji: "✈️", name: "airplane plane" },
  { emoji: "🛩️", name: "small airplane" },
  { emoji: "🛫", name: "airplane departure takeoff" },
  { emoji: "🛬", name: "airplane arrival landing" },
  { emoji: "🪂", name: "parachute" },
  { emoji: "💺", name: "seat" },
  { emoji: "🚁", name: "helicopter" },
  { emoji: "🚟", name: "suspension railway" },
  { emoji: "🚠", name: "mountain cableway" },
  { emoji: "🚡", name: "aerial tramway" },
  { emoji: "🛰️", name: "satellite" },
  { emoji: "🚀", name: "rocket launch" },
  { emoji: "🛸", name: "flying saucer ufo" },
  { emoji: "🛎️", name: "bellhop bell" },
  { emoji: "🧳", name: "luggage suitcase" },
  { emoji: "⌛", name: "hourglass time" },
  { emoji: "⏳", name: "hourglass flowing sand time" },
  { emoji: "⌚", name: "watch time" },
  { emoji: "⏰", name: "alarm clock time" },
  { emoji: "⏱️", name: "stopwatch timer" },
  { emoji: "⏲️", name: "timer clock" },
  { emoji: "🕰️", name: "mantelpiece clock" },
  { emoji: "🌑", name: "new moon" },
  { emoji: "🌒", name: "waxing crescent moon" },
  { emoji: "🌓", name: "first quarter moon" },
  { emoji: "🌔", name: "waxing gibbous moon" },
  { emoji: "🌕", name: "full moon" },
  { emoji: "🌖", name: "waning gibbous moon" },
  { emoji: "🌗", name: "last quarter moon" },
  { emoji: "🌘", name: "waning crescent moon" },
  { emoji: "🌙", name: "crescent moon night" },
  { emoji: "🌚", name: "new moon face" },
  { emoji: "🌛", name: "first quarter moon face" },
  { emoji: "🌜", name: "last quarter moon face" },
  { emoji: "🌡️", name: "thermometer temperature" },
  { emoji: "☀️", name: "sun sunny" },
  { emoji: "🌝", name: "full moon face" },
  { emoji: "🌞", name: "sun face" },
  { emoji: "🪐", name: "ringed planet saturn" },
  { emoji: "⭐", name: "star" },
  { emoji: "🌟", name: "glowing star" },
  { emoji: "🌠", name: "shooting star" },
  { emoji: "🌌", name: "milky way galaxy" },
  { emoji: "☁️", name: "cloud" },
  { emoji: "⛅", name: "sun behind cloud" },
  { emoji: "⛈️", name: "cloud lightning rain storm" },
  { emoji: "🌤️", name: "sun behind small cloud" },
  { emoji: "🌥️", name: "sun behind large cloud" },
  { emoji: "🌦️", name: "sun behind rain cloud" },
  { emoji: "🌧️", name: "cloud rain" },
  { emoji: "🌨️", name: "cloud snow" },
  { emoji: "🌩️", name: "cloud lightning" },
  { emoji: "🌪️", name: "tornado" },
  { emoji: "🌫️", name: "fog" },
  { emoji: "🌬️", name: "wind face" },
  { emoji: "🌀", name: "cyclone hurricane" },
  { emoji: "🌈", name: "rainbow" },
  { emoji: "🌂", name: "closed umbrella" },
  { emoji: "☂️", name: "umbrella" },
  { emoji: "☔", name: "umbrella rain drops" },
  { emoji: "⛱️", name: "umbrella ground beach" },
  { emoji: "⚡", name: "high voltage lightning zap bolt" },
  { emoji: "❄️", name: "snowflake cold winter" },
  { emoji: "☃️", name: "snowman" },
  { emoji: "⛄", name: "snowman without snow" },
  { emoji: "☄️", name: "comet" },
  { emoji: "🔥", name: "fire flame hot lit" },
  { emoji: "💧", name: "droplet water" },
  { emoji: "🌊", name: "water wave ocean" },

  // ── Activities & Sports ──
  { emoji: "🎃", name: "jack o lantern halloween pumpkin" },
  { emoji: "🎄", name: "christmas tree" },
  { emoji: "🎆", name: "fireworks" },
  { emoji: "🎇", name: "sparkler fireworks" },
  { emoji: "🧨", name: "firecracker" },
  { emoji: "✨", name: "sparkles magic stars" },
  { emoji: "🎈", name: "balloon party" },
  { emoji: "🎉", name: "party popper tada celebrate" },
  { emoji: "🎊", name: "confetti ball" },
  { emoji: "🎋", name: "tanabata tree" },
  { emoji: "🎍", name: "pine decoration" },
  { emoji: "🎎", name: "japanese dolls" },
  { emoji: "🎏", name: "carp streamer" },
  { emoji: "🎐", name: "wind chime" },
  { emoji: "🎑", name: "moon viewing ceremony" },
  { emoji: "🧧", name: "red envelope" },
  { emoji: "🎀", name: "ribbon bow" },
  { emoji: "🎁", name: "wrapped gift present" },
  { emoji: "🎗️", name: "reminder ribbon awareness" },
  { emoji: "🎟️", name: "admission tickets" },
  { emoji: "🎫", name: "ticket" },
  { emoji: "🎖️", name: "military medal" },
  { emoji: "🏆", name: "trophy award winner cup" },
  { emoji: "🏅", name: "sports medal" },
  { emoji: "🥇", name: "1st place medal gold" },
  { emoji: "🥈", name: "2nd place medal silver" },
  { emoji: "🥉", name: "3rd place medal bronze" },
  { emoji: "⚽", name: "soccer ball football" },
  { emoji: "⚾", name: "baseball" },
  { emoji: "🥎", name: "softball" },
  { emoji: "🏀", name: "basketball" },
  { emoji: "🏐", name: "volleyball" },
  { emoji: "🏈", name: "american football" },
  { emoji: "🏉", name: "rugby football" },
  { emoji: "🎾", name: "tennis" },
  { emoji: "🥏", name: "flying disc frisbee" },
  { emoji: "🎳", name: "bowling" },
  { emoji: "🏏", name: "cricket game bat" },
  { emoji: "🏑", name: "field hockey" },
  { emoji: "🏒", name: "ice hockey" },
  { emoji: "🥍", name: "lacrosse" },
  { emoji: "🏓", name: "ping pong table tennis" },
  { emoji: "🏸", name: "badminton" },
  { emoji: "🥊", name: "boxing glove" },
  { emoji: "🥋", name: "martial arts uniform" },
  { emoji: "🥅", name: "goal net" },
  { emoji: "⛳", name: "flag in hole golf" },
  { emoji: "⛸️", name: "ice skate" },
  { emoji: "🎣", name: "fishing pole" },
  { emoji: "🤿", name: "diving mask snorkel" },
  { emoji: "🎽", name: "running shirt" },
  { emoji: "🎿", name: "skis skiing" },
  { emoji: "🛷", name: "sled" },
  { emoji: "🥌", name: "curling stone" },
  { emoji: "🎯", name: "bullseye target dart" },
  { emoji: "🪀", name: "yo-yo" },
  { emoji: "🪁", name: "kite" },
  { emoji: "🔫", name: "water pistol gun" },
  { emoji: "🎱", name: "pool 8 ball billiards" },
  { emoji: "🔮", name: "crystal ball fortune" },
  { emoji: "🪄", name: "magic wand" },
  { emoji: "🎮", name: "video game controller" },
  { emoji: "🕹️", name: "joystick game" },
  { emoji: "🎰", name: "slot machine casino" },
  { emoji: "🎲", name: "game die dice" },
  { emoji: "🧩", name: "puzzle piece jigsaw" },
  { emoji: "🧸", name: "teddy bear" },
  { emoji: "🪅", name: "pinata" },
  { emoji: "🪩", name: "mirror ball disco" },
  { emoji: "🪆", name: "nesting dolls matryoshka" },
  { emoji: "♠️", name: "spade suit cards" },
  { emoji: "♥️", name: "heart suit cards" },
  { emoji: "♦️", name: "diamond suit cards" },
  { emoji: "♣️", name: "club suit cards" },
  { emoji: "♟️", name: "chess pawn" },
  { emoji: "🃏", name: "joker card" },
  { emoji: "🀄", name: "mahjong red dragon" },
  { emoji: "🎴", name: "flower playing cards" },
  { emoji: "🎭", name: "performing arts theater drama" },
  { emoji: "🖼️", name: "framed picture painting" },
  { emoji: "🎨", name: "artist palette paint art" },
  { emoji: "🧵", name: "thread sewing" },
  { emoji: "🪡", name: "sewing needle" },
  { emoji: "🧶", name: "yarn knitting" },
  { emoji: "🪢", name: "knot rope" },

  // ── Objects ──
  { emoji: "👓", name: "glasses eyeglasses" },
  { emoji: "🕶️", name: "sunglasses" },
  { emoji: "🥽", name: "goggles" },
  { emoji: "🥼", name: "lab coat" },
  { emoji: "🦺", name: "safety vest" },
  { emoji: "👔", name: "necktie" },
  { emoji: "👕", name: "t-shirt tee" },
  { emoji: "👖", name: "jeans pants" },
  { emoji: "🧣", name: "scarf" },
  { emoji: "🧤", name: "gloves" },
  { emoji: "🧥", name: "coat jacket" },
  { emoji: "🧦", name: "socks" },
  { emoji: "👗", name: "dress" },
  { emoji: "👘", name: "kimono" },
  { emoji: "🥻", name: "sari" },
  { emoji: "🩱", name: "one piece swimsuit" },
  { emoji: "🩲", name: "briefs underwear" },
  { emoji: "🩳", name: "shorts" },
  { emoji: "👙", name: "bikini" },
  { emoji: "👚", name: "woman clothes" },
  { emoji: "👛", name: "purse" },
  { emoji: "👜", name: "handbag" },
  { emoji: "👝", name: "clutch bag" },
  { emoji: "🛍️", name: "shopping bags" },
  { emoji: "🎒", name: "backpack school bag" },
  { emoji: "🩴", name: "thong sandal flip flop" },
  { emoji: "👞", name: "man shoe" },
  { emoji: "👟", name: "running shoe sneaker" },
  { emoji: "🥾", name: "hiking boot" },
  { emoji: "🥿", name: "flat shoe" },
  { emoji: "👠", name: "high heeled shoe" },
  { emoji: "👡", name: "woman sandal" },
  { emoji: "🩰", name: "ballet shoes" },
  { emoji: "👢", name: "woman boot" },
  { emoji: "🪮", name: "hair pick comb" },
  { emoji: "👑", name: "crown king queen" },
  { emoji: "👒", name: "woman hat" },
  { emoji: "🎩", name: "top hat" },
  { emoji: "🎓", name: "graduation cap" },
  { emoji: "🧢", name: "billed cap baseball" },
  { emoji: "🪖", name: "military helmet" },
  { emoji: "⛑️", name: "rescue worker helmet" },
  { emoji: "📿", name: "prayer beads" },
  { emoji: "💄", name: "lipstick makeup" },
  { emoji: "💍", name: "ring diamond engagement" },
  { emoji: "💎", name: "gem stone diamond jewel" },
  { emoji: "🔇", name: "muted speaker" },
  { emoji: "🔈", name: "speaker low volume" },
  { emoji: "🔉", name: "speaker medium volume" },
  { emoji: "🔊", name: "speaker high volume loud" },
  { emoji: "📢", name: "loudspeaker megaphone" },
  { emoji: "📣", name: "megaphone" },
  { emoji: "📯", name: "postal horn" },
  { emoji: "🔔", name: "bell notification" },
  { emoji: "🔕", name: "bell slash mute" },
  { emoji: "🎼", name: "musical score" },
  { emoji: "🎵", name: "musical note music" },
  { emoji: "🎶", name: "musical notes music" },
  { emoji: "🎙️", name: "studio microphone podcast" },
  { emoji: "🎚️", name: "level slider" },
  { emoji: "🎛️", name: "control knobs" },
  { emoji: "🎤", name: "microphone karaoke" },
  { emoji: "🎧", name: "headphone headset" },
  { emoji: "📻", name: "radio" },
  { emoji: "🎷", name: "saxophone sax" },
  { emoji: "🪗", name: "accordion" },
  { emoji: "🎸", name: "guitar" },
  { emoji: "🎹", name: "musical keyboard piano" },
  { emoji: "🎺", name: "trumpet" },
  { emoji: "🎻", name: "violin" },
  { emoji: "🪕", name: "banjo" },
  { emoji: "🥁", name: "drum" },
  { emoji: "🪘", name: "long drum" },
  { emoji: "🪇", name: "maracas" },
  { emoji: "🪈", name: "flute" },
  { emoji: "📱", name: "mobile phone cell" },
  { emoji: "📲", name: "mobile phone arrow" },
  { emoji: "☎️", name: "telephone phone" },
  { emoji: "📞", name: "telephone receiver" },
  { emoji: "📟", name: "pager" },
  { emoji: "📠", name: "fax machine" },
  { emoji: "🔋", name: "battery" },
  { emoji: "🪫", name: "low battery" },
  { emoji: "🔌", name: "electric plug" },
  { emoji: "💻", name: "laptop computer" },
  { emoji: "🖥️", name: "desktop computer monitor" },
  { emoji: "🖨️", name: "printer" },
  { emoji: "⌨️", name: "keyboard" },
  { emoji: "🖱️", name: "computer mouse" },
  { emoji: "🖲️", name: "trackball" },
  { emoji: "💽", name: "computer disk minidisc" },
  { emoji: "💾", name: "floppy disk save" },
  { emoji: "💿", name: "optical disk cd" },
  { emoji: "📀", name: "dvd" },
  { emoji: "🧮", name: "abacus" },
  { emoji: "🎥", name: "movie camera film" },
  { emoji: "🎞️", name: "film frames" },
  { emoji: "📽️", name: "film projector" },
  { emoji: "🎬", name: "clapper board movie action" },
  { emoji: "📺", name: "television tv" },
  { emoji: "📷", name: "camera photo" },
  { emoji: "📸", name: "camera flash photo" },
  { emoji: "📹", name: "video camera" },
  { emoji: "📼", name: "videocassette vhs" },
  { emoji: "🔍", name: "magnifying glass search left" },
  { emoji: "🔎", name: "magnifying glass search right" },
  { emoji: "🕯️", name: "candle" },
  { emoji: "💡", name: "light bulb idea" },
  { emoji: "🔦", name: "flashlight torch" },
  { emoji: "🏮", name: "red paper lantern" },
  { emoji: "🪔", name: "diya lamp" },
  { emoji: "📔", name: "notebook decorative cover" },
  { emoji: "📕", name: "closed book" },
  { emoji: "📖", name: "open book reading" },
  { emoji: "📗", name: "green book" },
  { emoji: "📘", name: "blue book" },
  { emoji: "📙", name: "orange book" },
  { emoji: "📚", name: "books library stack" },
  { emoji: "📓", name: "notebook" },
  { emoji: "📒", name: "ledger" },
  { emoji: "📃", name: "page curl" },
  { emoji: "📜", name: "scroll" },
  { emoji: "📄", name: "page facing up document" },
  { emoji: "📰", name: "newspaper" },
  { emoji: "🗞️", name: "rolled up newspaper" },
  { emoji: "📑", name: "bookmark tabs" },
  { emoji: "🔖", name: "bookmark" },
  { emoji: "🏷️", name: "label tag" },
  { emoji: "💰", name: "money bag" },
  { emoji: "🪙", name: "coin" },
  { emoji: "💴", name: "yen banknote" },
  { emoji: "💵", name: "dollar banknote money" },
  { emoji: "💶", name: "euro banknote" },
  { emoji: "💷", name: "pound banknote" },
  { emoji: "💸", name: "money wings flying" },
  { emoji: "💳", name: "credit card" },
  { emoji: "🧾", name: "receipt" },
  { emoji: "💹", name: "chart increasing yen" },
  { emoji: "✉️", name: "envelope email mail" },
  { emoji: "📧", name: "e-mail email" },
  { emoji: "📨", name: "incoming envelope" },
  { emoji: "📩", name: "envelope arrow" },
  { emoji: "📤", name: "outbox tray" },
  { emoji: "📥", name: "inbox tray" },
  { emoji: "📦", name: "package box" },
  { emoji: "📫", name: "closed mailbox raised flag" },
  { emoji: "📪", name: "closed mailbox lowered flag" },
  { emoji: "📬", name: "open mailbox raised flag" },
  { emoji: "📭", name: "open mailbox lowered flag" },
  { emoji: "📮", name: "postbox" },
  { emoji: "🗳️", name: "ballot box" },
  { emoji: "✏️", name: "pencil" },
  { emoji: "✒️", name: "black nib pen" },
  { emoji: "🖋️", name: "fountain pen" },
  { emoji: "🖊️", name: "pen" },
  { emoji: "🖌️", name: "paintbrush" },
  { emoji: "🖍️", name: "crayon" },
  { emoji: "📝", name: "memo note write" },
  { emoji: "💼", name: "briefcase business" },
  { emoji: "📁", name: "file folder" },
  { emoji: "📂", name: "open file folder" },
  { emoji: "🗂️", name: "card index dividers" },
  { emoji: "📅", name: "calendar date" },
  { emoji: "📆", name: "tear off calendar" },
  { emoji: "🗒️", name: "spiral notepad" },
  { emoji: "🗓️", name: "spiral calendar" },
  { emoji: "📇", name: "card index" },
  { emoji: "📈", name: "chart increasing trending up" },
  { emoji: "📉", name: "chart decreasing trending down" },
  { emoji: "📊", name: "bar chart graph" },
  { emoji: "📋", name: "clipboard" },
  { emoji: "📌", name: "pushpin pin" },
  { emoji: "📍", name: "round pushpin location" },
  { emoji: "📎", name: "paperclip attach" },
  { emoji: "🖇️", name: "linked paperclips" },
  { emoji: "📏", name: "straight ruler" },
  { emoji: "📐", name: "triangular ruler" },
  { emoji: "✂️", name: "scissors cut" },
  { emoji: "🗃️", name: "card file box" },
  { emoji: "🗄️", name: "file cabinet" },
  { emoji: "🗑️", name: "wastebasket trash delete" },
  { emoji: "🔒", name: "locked lock secure" },
  { emoji: "🔓", name: "unlocked open lock" },
  { emoji: "🔏", name: "locked pen" },
  { emoji: "🔐", name: "locked key" },
  { emoji: "🔑", name: "key" },
  { emoji: "🗝️", name: "old key" },
  { emoji: "🔨", name: "hammer tool" },
  { emoji: "🪓", name: "axe" },
  { emoji: "⛏️", name: "pick" },
  { emoji: "⚒️", name: "hammer pick" },
  { emoji: "🛠️", name: "hammer wrench tools" },
  { emoji: "🗡️", name: "dagger knife sword" },
  { emoji: "⚔️", name: "crossed swords" },
  { emoji: "💣", name: "bomb" },
  { emoji: "🪃", name: "boomerang" },
  { emoji: "🏹", name: "bow arrow" },
  { emoji: "🛡️", name: "shield" },
  { emoji: "🪚", name: "carpentry saw" },
  { emoji: "🔧", name: "wrench spanner tool" },
  { emoji: "🪛", name: "screwdriver" },
  { emoji: "🔩", name: "nut bolt" },
  { emoji: "⚙️", name: "gear cog settings" },
  { emoji: "🗜️", name: "clamp" },
  { emoji: "⚖️", name: "balance scale" },
  { emoji: "🦯", name: "white cane" },
  { emoji: "🔗", name: "link chain url" },
  { emoji: "⛓️", name: "chains" },
  { emoji: "🪝", name: "hook" },
  { emoji: "🧰", name: "toolbox" },
  { emoji: "🧲", name: "magnet" },
  { emoji: "🪜", name: "ladder" },
  { emoji: "⚗️", name: "alembic chemistry" },
  { emoji: "🧪", name: "test tube science" },
  { emoji: "🧫", name: "petri dish lab" },
  { emoji: "🧬", name: "dna double helix" },
  { emoji: "🔬", name: "microscope science" },
  { emoji: "🔭", name: "telescope" },
  { emoji: "📡", name: "satellite antenna dish" },
  { emoji: "💉", name: "syringe needle vaccine" },
  { emoji: "🩸", name: "drop blood" },
  { emoji: "💊", name: "pill medicine drug" },
  { emoji: "🩹", name: "adhesive bandage band-aid" },
  { emoji: "🩼", name: "crutch" },
  { emoji: "🩺", name: "stethoscope doctor" },
  { emoji: "🩻", name: "x-ray" },
  { emoji: "🚪", name: "door" },
  { emoji: "🛗", name: "elevator" },
  { emoji: "🪞", name: "mirror" },
  { emoji: "🪟", name: "window" },
  { emoji: "🛏️", name: "bed" },
  { emoji: "🛋️", name: "couch lamp" },
  { emoji: "🪑", name: "chair seat" },
  { emoji: "🚽", name: "toilet" },
  { emoji: "🪠", name: "plunger" },
  { emoji: "🚿", name: "shower" },
  { emoji: "🛁", name: "bathtub bath" },
  { emoji: "🪤", name: "mouse trap" },
  { emoji: "🪒", name: "razor" },
  { emoji: "🧴", name: "lotion bottle" },
  { emoji: "🧷", name: "safety pin" },
  { emoji: "🧹", name: "broom" },
  { emoji: "🧺", name: "basket laundry" },
  { emoji: "🧻", name: "roll paper toilet" },
  { emoji: "🪣", name: "bucket" },
  { emoji: "🧼", name: "soap" },
  { emoji: "🫧", name: "bubbles" },
  { emoji: "🪥", name: "toothbrush" },
  { emoji: "🧽", name: "sponge" },
  { emoji: "🧯", name: "fire extinguisher" },
  { emoji: "🛒", name: "shopping cart trolley" },
  { emoji: "🚬", name: "cigarette smoking" },
  { emoji: "⚰️", name: "coffin" },
  { emoji: "🪦", name: "headstone gravestone" },
  { emoji: "⚱️", name: "funeral urn" },
  { emoji: "🧿", name: "nazar amulet evil eye" },
  { emoji: "🪬", name: "hamsa" },
  { emoji: "🗿", name: "moai statue" },
  { emoji: "🪧", name: "placard sign" },
  { emoji: "🪪", name: "identification card id" },

  // ── Symbols ──
  { emoji: "🏧", name: "atm sign" },
  { emoji: "🚮", name: "litter bin" },
  { emoji: "🚰", name: "potable water" },
  { emoji: "♿", name: "wheelchair accessible" },
  { emoji: "🚹", name: "men room" },
  { emoji: "🚺", name: "women room" },
  { emoji: "🚻", name: "restroom" },
  { emoji: "🚼", name: "baby symbol" },
  { emoji: "🚾", name: "water closet wc" },
  { emoji: "🛂", name: "passport control" },
  { emoji: "🛃", name: "customs" },
  { emoji: "🛄", name: "baggage claim" },
  { emoji: "🛅", name: "left luggage" },
  { emoji: "⚠️", name: "warning caution" },
  { emoji: "🚸", name: "children crossing" },
  { emoji: "⛔", name: "no entry forbidden" },
  { emoji: "🚫", name: "prohibited forbidden" },
  { emoji: "🚳", name: "no bicycles" },
  { emoji: "🚭", name: "no smoking" },
  { emoji: "🚯", name: "no littering" },
  { emoji: "🚱", name: "non potable water" },
  { emoji: "🚷", name: "no pedestrians" },
  { emoji: "📵", name: "no mobile phones" },
  { emoji: "🔞", name: "no one under eighteen" },
  { emoji: "☢️", name: "radioactive" },
  { emoji: "☣️", name: "biohazard" },
  { emoji: "⬆️", name: "up arrow" },
  { emoji: "↗️", name: "up right arrow" },
  { emoji: "➡️", name: "right arrow" },
  { emoji: "↘️", name: "down right arrow" },
  { emoji: "⬇️", name: "down arrow" },
  { emoji: "↙️", name: "down left arrow" },
  { emoji: "⬅️", name: "left arrow" },
  { emoji: "↖️", name: "up left arrow" },
  { emoji: "↕️", name: "up down arrow" },
  { emoji: "↔️", name: "left right arrow" },
  { emoji: "↩️", name: "right arrow curving left" },
  { emoji: "↪️", name: "left arrow curving right" },
  { emoji: "⤴️", name: "right arrow curving up" },
  { emoji: "⤵️", name: "right arrow curving down" },
  { emoji: "🔃", name: "clockwise arrows" },
  { emoji: "🔄", name: "counterclockwise arrows refresh" },
  { emoji: "🔙", name: "back arrow" },
  { emoji: "🔚", name: "end arrow" },
  { emoji: "🔛", name: "on arrow" },
  { emoji: "🔜", name: "soon arrow" },
  { emoji: "🔝", name: "top arrow" },
  { emoji: "🛐", name: "place worship" },
  { emoji: "⚛️", name: "atom symbol" },
  { emoji: "🕉️", name: "om" },
  { emoji: "✡️", name: "star david" },
  { emoji: "☸️", name: "wheel dharma" },
  { emoji: "☯️", name: "yin yang" },
  { emoji: "✝️", name: "latin cross" },
  { emoji: "☦️", name: "orthodox cross" },
  { emoji: "☪️", name: "star crescent" },
  { emoji: "☮️", name: "peace symbol" },
  { emoji: "🕎", name: "menorah" },
  { emoji: "🔯", name: "six pointed star" },
  { emoji: "♈", name: "aries zodiac" },
  { emoji: "♉", name: "taurus zodiac" },
  { emoji: "♊", name: "gemini zodiac" },
  { emoji: "♋", name: "cancer zodiac" },
  { emoji: "♌", name: "leo zodiac" },
  { emoji: "♍", name: "virgo zodiac" },
  { emoji: "♎", name: "libra zodiac" },
  { emoji: "♏", name: "scorpio zodiac" },
  { emoji: "♐", name: "sagittarius zodiac" },
  { emoji: "♑", name: "capricorn zodiac" },
  { emoji: "♒", name: "aquarius zodiac" },
  { emoji: "♓", name: "pisces zodiac" },
  { emoji: "⛎", name: "ophiuchus zodiac" },
  { emoji: "🔀", name: "shuffle tracks" },
  { emoji: "🔁", name: "repeat" },
  { emoji: "🔂", name: "repeat single" },
  { emoji: "▶️", name: "play button" },
  { emoji: "⏩", name: "fast forward" },
  { emoji: "⏭️", name: "next track" },
  { emoji: "⏯️", name: "play pause" },
  { emoji: "◀️", name: "reverse button" },
  { emoji: "⏪", name: "fast reverse rewind" },
  { emoji: "⏮️", name: "last track" },
  { emoji: "🔼", name: "upwards button" },
  { emoji: "⏫", name: "fast up" },
  { emoji: "🔽", name: "downwards button" },
  { emoji: "⏬", name: "fast down" },
  { emoji: "⏸️", name: "pause button" },
  { emoji: "⏹️", name: "stop button" },
  { emoji: "⏺️", name: "record button" },
  { emoji: "⏏️", name: "eject button" },
  { emoji: "🎦", name: "cinema film" },
  { emoji: "🔅", name: "dim button brightness low" },
  { emoji: "🔆", name: "bright button brightness high" },
  { emoji: "📶", name: "antenna bars signal" },
  { emoji: "🛜", name: "wireless wifi" },
  { emoji: "📳", name: "vibration mode" },
  { emoji: "📴", name: "mobile phone off" },
  { emoji: "♀️", name: "female sign" },
  { emoji: "♂️", name: "male sign" },
  { emoji: "⚧️", name: "transgender symbol" },
  { emoji: "✖️", name: "multiply heavy multiplication" },
  { emoji: "➕", name: "plus" },
  { emoji: "➖", name: "minus" },
  { emoji: "➗", name: "divide division" },
  { emoji: "🟰", name: "heavy equals sign" },
  { emoji: "♾️", name: "infinity" },
  { emoji: "‼️", name: "double exclamation mark" },
  { emoji: "⁉️", name: "exclamation question mark" },
  { emoji: "❓", name: "question mark red" },
  { emoji: "❔", name: "question mark white" },
  { emoji: "❕", name: "exclamation mark white" },
  { emoji: "❗", name: "exclamation mark red alert" },
  { emoji: "〰️", name: "wavy dash" },
  { emoji: "💱", name: "currency exchange" },
  { emoji: "💲", name: "heavy dollar sign" },
  { emoji: "⚕️", name: "medical symbol" },
  { emoji: "♻️", name: "recycling symbol recycle" },
  { emoji: "⚜️", name: "fleur-de-lis" },
  { emoji: "🔱", name: "trident emblem" },
  { emoji: "📛", name: "name badge" },
  { emoji: "🔰", name: "japanese symbol beginner" },
  { emoji: "⭕", name: "hollow red circle" },
  { emoji: "✅", name: "check mark button done" },
  { emoji: "☑️", name: "check box check" },
  { emoji: "✔️", name: "check mark" },
  { emoji: "❌", name: "cross mark no wrong" },
  { emoji: "❎", name: "cross mark button" },
  { emoji: "➰", name: "curly loop" },
  { emoji: "➿", name: "double curly loop" },
  { emoji: "〽️", name: "part alternation mark" },
  { emoji: "✳️", name: "eight spoked asterisk" },
  { emoji: "✴️", name: "eight pointed star" },
  { emoji: "❇️", name: "sparkle" },
  { emoji: "©️", name: "copyright" },
  { emoji: "®️", name: "registered" },
  { emoji: "™️", name: "trade mark" },
  { emoji: "#️⃣", name: "keycap hash number" },
  { emoji: "*️⃣", name: "keycap asterisk star" },
  { emoji: "0️⃣", name: "keycap zero" },
  { emoji: "1️⃣", name: "keycap one" },
  { emoji: "2️⃣", name: "keycap two" },
  { emoji: "3️⃣", name: "keycap three" },
  { emoji: "4️⃣", name: "keycap four" },
  { emoji: "5️⃣", name: "keycap five" },
  { emoji: "6️⃣", name: "keycap six" },
  { emoji: "7️⃣", name: "keycap seven" },
  { emoji: "8️⃣", name: "keycap eight" },
  { emoji: "9️⃣", name: "keycap nine" },
  { emoji: "🔟", name: "keycap ten" },
  { emoji: "🔠", name: "input latin uppercase" },
  { emoji: "🔡", name: "input latin lowercase" },
  { emoji: "🔢", name: "input numbers" },
  { emoji: "🔣", name: "input symbols" },
  { emoji: "🔤", name: "input latin letters" },
  { emoji: "🅰️", name: "a button blood type" },
  { emoji: "🆎", name: "ab button blood type" },
  { emoji: "🅱️", name: "b button blood type" },
  { emoji: "🆑", name: "cl button" },
  { emoji: "🆒", name: "cool button" },
  { emoji: "🆓", name: "free button" },
  { emoji: "ℹ️", name: "information" },
  { emoji: "🆔", name: "id button" },
  { emoji: "Ⓜ️", name: "circled m" },
  { emoji: "🆕", name: "new button" },
  { emoji: "🆖", name: "ng button" },
  { emoji: "🅾️", name: "o button blood type" },
  { emoji: "🆗", name: "ok button" },
  { emoji: "🅿️", name: "p button parking" },
  { emoji: "🆘", name: "sos button emergency" },
  { emoji: "🆙", name: "up button" },
  { emoji: "🆚", name: "vs button versus" },
  { emoji: "🈁", name: "japanese here" },
  { emoji: "🈂️", name: "japanese service charge" },
  { emoji: "🈷️", name: "japanese monthly amount" },
  { emoji: "🈶", name: "japanese not free charge" },
  { emoji: "🈯", name: "japanese reserved" },
  { emoji: "🉐", name: "japanese bargain" },
  { emoji: "🈹", name: "japanese discount" },
  { emoji: "🈚", name: "japanese free charge" },
  { emoji: "🈲", name: "japanese prohibited" },
  { emoji: "🉑", name: "japanese acceptable" },
  { emoji: "🈸", name: "japanese application" },
  { emoji: "🈴", name: "japanese passing grade" },
  { emoji: "🈳", name: "japanese vacancy" },
  { emoji: "㊗️", name: "japanese congratulations" },
  { emoji: "㊙️", name: "japanese secret" },
  { emoji: "🈺", name: "japanese open business" },
  { emoji: "🈵", name: "japanese no vacancy" },
  { emoji: "🔴", name: "red circle" },
  { emoji: "🟠", name: "orange circle" },
  { emoji: "🟡", name: "yellow circle" },
  { emoji: "🟢", name: "green circle" },
  { emoji: "🔵", name: "blue circle" },
  { emoji: "🟣", name: "purple circle" },
  { emoji: "🟤", name: "brown circle" },
  { emoji: "⚫", name: "black circle" },
  { emoji: "⚪", name: "white circle" },
  { emoji: "🟥", name: "red square" },
  { emoji: "🟧", name: "orange square" },
  { emoji: "🟨", name: "yellow square" },
  { emoji: "🟩", name: "green square" },
  { emoji: "🟦", name: "blue square" },
  { emoji: "🟪", name: "purple square" },
  { emoji: "🟫", name: "brown square" },
  { emoji: "⬛", name: "black large square" },
  { emoji: "⬜", name: "white large square" },
  { emoji: "◼️", name: "black medium square" },
  { emoji: "◻️", name: "white medium square" },
  { emoji: "◾", name: "black medium small square" },
  { emoji: "◽", name: "white medium small square" },
  { emoji: "▪️", name: "black small square" },
  { emoji: "▫️", name: "white small square" },
  { emoji: "🔶", name: "large orange diamond" },
  { emoji: "🔷", name: "large blue diamond" },
  { emoji: "🔸", name: "small orange diamond" },
  { emoji: "🔹", name: "small blue diamond" },
  { emoji: "🔺", name: "red triangle pointed up" },
  { emoji: "🔻", name: "red triangle pointed down" },
  { emoji: "💠", name: "diamond dot" },
  { emoji: "🔘", name: "radio button" },
  { emoji: "🔳", name: "white square button" },
  { emoji: "🔲", name: "black square button" },

  // ── Flags (common) ──
  { emoji: "🏁", name: "chequered flag checkered finish" },
  { emoji: "🚩", name: "triangular flag red flag" },
  { emoji: "🎌", name: "crossed flags" },
  { emoji: "🏴", name: "black flag" },
  { emoji: "🏳️", name: "white flag" },
  { emoji: "🏳️‍🌈", name: "rainbow flag pride" },
  { emoji: "🏳️‍⚧️", name: "transgender flag" },
  { emoji: "🏴‍☠️", name: "pirate flag jolly roger" },
  { emoji: "🇺🇸", name: "flag united states usa america" },
  { emoji: "🇬🇧", name: "flag united kingdom uk britain" },
  { emoji: "🇨🇦", name: "flag canada" },
  { emoji: "🇦🇺", name: "flag australia" },
  { emoji: "🇫🇷", name: "flag france" },
  { emoji: "🇩🇪", name: "flag germany" },
  { emoji: "🇮🇹", name: "flag italy" },
  { emoji: "🇪🇸", name: "flag spain" },
  { emoji: "🇯🇵", name: "flag japan" },
  { emoji: "🇰🇷", name: "flag south korea" },
  { emoji: "🇨🇳", name: "flag china" },
  { emoji: "🇮🇳", name: "flag india" },
  { emoji: "🇧🇷", name: "flag brazil" },
  { emoji: "🇲🇽", name: "flag mexico" },
  { emoji: "🇷🇺", name: "flag russia" },
  { emoji: "🇿🇦", name: "flag south africa" },
  { emoji: "🇳🇬", name: "flag nigeria" },
  { emoji: "🇪🇬", name: "flag egypt" },
  { emoji: "🇹🇷", name: "flag turkey" },
  { emoji: "🇸🇦", name: "flag saudi arabia" },
  { emoji: "🇦🇪", name: "flag united arab emirates uae" },
  { emoji: "🇸🇪", name: "flag sweden" },
  { emoji: "🇳🇴", name: "flag norway" },
  { emoji: "🇩🇰", name: "flag denmark" },
  { emoji: "🇫🇮", name: "flag finland" },
  { emoji: "🇳🇱", name: "flag netherlands" },
  { emoji: "🇧🇪", name: "flag belgium" },
  { emoji: "🇨🇭", name: "flag switzerland" },
  { emoji: "🇦🇹", name: "flag austria" },
  { emoji: "🇵🇹", name: "flag portugal" },
  { emoji: "🇬🇷", name: "flag greece" },
  { emoji: "🇵🇱", name: "flag poland" },
  { emoji: "🇮🇪", name: "flag ireland" },
  { emoji: "🇮🇱", name: "flag israel" },
  { emoji: "🇹🇭", name: "flag thailand" },
  { emoji: "🇻🇳", name: "flag vietnam" },
  { emoji: "🇵🇭", name: "flag philippines" },
  { emoji: "🇮🇩", name: "flag indonesia" },
  { emoji: "🇲🇾", name: "flag malaysia" },
  { emoji: "🇸🇬", name: "flag singapore" },
  { emoji: "🇳🇿", name: "flag new zealand" },
  { emoji: "🇦🇷", name: "flag argentina" },
  { emoji: "🇨🇴", name: "flag colombia" },
  { emoji: "🇨🇱", name: "flag chile" },
  { emoji: "🇵🇪", name: "flag peru" },
  { emoji: "🇺🇦", name: "flag ukraine" },
  { emoji: "🇷🇴", name: "flag romania" },
  { emoji: "🇭🇺", name: "flag hungary" },
  { emoji: "🇨🇿", name: "flag czech republic czechia" },
  { emoji: "🇭🇷", name: "flag croatia" },
  { emoji: "🇷🇸", name: "flag serbia" },
  { emoji: "🇰🇪", name: "flag kenya" },
  { emoji: "🇪🇹", name: "flag ethiopia" },
  { emoji: "🇬🇭", name: "flag ghana" },
  { emoji: "🇵🇰", name: "flag pakistan" },
  { emoji: "🇧🇩", name: "flag bangladesh" },
  { emoji: "🇱🇰", name: "flag sri lanka" },
  { emoji: "🇲🇲", name: "flag myanmar burma" },
  { emoji: "🇭🇰", name: "flag hong kong" },
  { emoji: "🇹🇼", name: "flag taiwan" },
];
